### PR TITLE
stale issues

### PR DESCRIPTION
**Pull request by AfterNetwork**

### CODE REVIEW

**Comment by smileycreations15** [comment]
am i going blind or am i seeing just edits that is expected to work out of the box but does not...

**Comment by smileycreations15** [comment]
idk...

**Comment by AfterNetwork** [comment]
I fixed it up a little bit.

**Comment by AfterNetwork** [comment]
now?

**Comment by AfterNetwork** [comment]
let's put smile.js in the repo

**Comment by AfterNetwork** [comment]
smile.js in the smile.js org

**Comment by AfterNetwork** [comment]
review it already

**Comment by AfterNetwork** [comment]
@smileycreations15

**Comment by AfterNetwork** [comment]
@smileycreations15

**Comment by smileycreations15** [comment]
NOOOOO STOP PINGIN ME

**Comment by AfterNetwork** [comment]
review it and put this repo in the smile.js repo

**Comment by smileycreations15** [comment]
n. o.

**Comment by AfterNetwork** [comment]
all checks have passed though

**Comment by AfterNetwork** [comment]
I have edited it.

**Comment by smileycreations15** [comment]
well no

**Comment by AfterNetwork** [comment]
Well, I will edit it after you approve it.

**Comment by AfterNetwork** [comment]
(lol maybe another .dummy file)

**Comment by smileycreations15** [comment]
lol but we dont need stale check

**Comment by AfterNetwork** [comment]
fine

**Pull request closed without merging**
