### PR TITLE
auto-label issues

### PR DESCRIPTION
**Pull request by AfterNetwork**

### CODE REVIEW

**Comment by smileycreations15** [comment]
failing checks.

**Comment by AfterNetwork** [comment]
> failing checks.

.yml also due to the label thing only

**Comment by AfterNetwork** [comment]
EVERYTHING EXCEPT THE LABELER

**Comment by AfterNetwork** [comment]
the requestsed item

**Comment by smileycreations15** [comment]
all checks shall pass...

**Comment by AfterNetwork** [comment]
fix it

**Comment by AfterNetwork** [comment]
because think of it

**Comment by smileycreations15** [comment]
you created the pr

**Comment by AfterNetwork** [comment]
> you created the pr

fix the PR

**Comment by AfterNetwork** [comment]
fix it, i dunno how to

**Comment by smileycreations15** [comment]
i dunno too

**Comment by AfterNetwork** [comment]
bye

**Pull request closed without merging**
