### PR TITLE
Use Node.js LTS 10 and above / support all major OSes

### PR DESCRIPTION
**Pull request by AfterNetwork**
DO IT

### CODE REVIEW

**Comment by smileycreations15** [comment]
no

**Comment by smileycreations15** [comment]
all version testing

**Comment by AfterNetwork** [comment]
Node.js must successful in node.js 10 or above.
(dis is for better preformance and so it changes it)

**Comment by smileycreations15** [comment]
I BROKE THE WORKFLOW

**Comment by AfterNetwork** [comment]
merge is conflicted with something so test with 10, 11 and 12

**Comment by smileycreations15** [comment]
im on it

**Comment by AfterNetwork** [comment]
Smile.js is for Node.js 10 or above for better preformance and also to prevent conflict with older versions that might not be supported.

**Comment by smileycreations15** [comment]
yes

**Comment by AfterNetwork** [comment]
SO merge this

**Comment by smileycreations15** [comment]
TONS OF TESTS PUSHED.

**Comment by AfterNetwork** [comment]
so, all major OSes are now supported

**Comment by smileycreations15** [comment]
yes

**Comment by AfterNetwork** [comment]
list of more OSes need to be supported:
fedora
debrian
lubuntu
ubuntu

**Comment by smileycreations15** [comment]
(ubuntu is the biggest one)

**Comment by smileycreations15** [comment]
nodejs on windows will not be supported

**Comment by smileycreations15** [comment]
Merging.

**Comment by smileycreations15** [comment]
done

**Comment by AfterNetwork** [comment]
okay.
but we need windows.
69% of users in the world is windows

**Comment by smileycreations15** [comment]
but they use browsers

**Comment by smileycreations15** [comment]
not node apps

**Comment by smileycreations15** [comment]
also we are building a custom discord pls help @AfterNetwork

**Comment by AfterNetwork** [comment]
it's for developers

**Comment by AfterNetwork** [comment]
go create somethiing like discord

**Comment by smileycreations15** [comment]
DIS

**Comment by smileycreations15** [comment]
smileycreations15/WebChat

**Comment by smileycreations15** [comment]
https://github.com/smileycreations15/WebChat

**Comment by AfterNetwork** [comment]
put it on a website

**Comment by smileycreations15** [comment]
well

**Comment by smileycreations15** [comment]
i put it on heroku

**Comment by smileycreations15** [comment]
but there is nothing yet

**Comment by AfterNetwork** [comment]
application error

**Comment by smileycreations15** [comment]
well

**Comment by smileycreations15** [comment]
yea

**Comment by AfterNetwork** [comment]
put it

**Comment by smileycreations15** [comment]
note: i need to get back on good wifi to host the server

**Comment by AfterNetwork** [comment]
are u on good wifi

**Comment by smileycreations15** [comment]
no

**Comment by smileycreations15** [comment]
i need to set up port redirects

**Comment by AfterNetwork** [comment]
uh oh

**Comment by smileycreations15** [comment]
so i need to leave a server running

**Comment by smileycreations15** [comment]
(docker containers?)

**Comment by smileycreations15** [comment]
@AfterNetwork

**Pull request merged**
