### PR TITLE
auto-node.js package

### PR DESCRIPTION
**Pull request by AfterNetwork**

### CODE REVIEW

**Comment by smileycreations15** [comment]
it does not work out of the box.

**Comment by AfterNetwork** [comment]
but it still does it

**Comment by AfterNetwork** [comment]
so approve it already

**Comment by smileycreations15** [comment]
no. i  will not

**Comment by smileycreations15** [comment]
it does not work OOTB

**Comment by AfterNetwork** [comment]
We could modify it

**Comment by AfterNetwork** [comment]
just approve it

**Comment by smileycreations15** [comment]
but well... no

**Comment by smileycreations15** [comment]
dont beg to be approved

**Comment by AfterNetwork** [comment]
fuck

**Comment by AfterNetwork** [comment]
oof language

**Comment by AfterNetwork** [comment]
excuse my language

**Comment by smileycreations15** [comment]
okay

**Comment by AfterNetwork** [comment]
-closed-

**Pull request closed without merging**
